-- =============================================================
-- 中国人形机器人上游核心零部件企业数据导入
-- 数据来源：AMORA研究团队整理（2026-03-29）
-- 分类：减速器 | 电机/执行器 | 传感器 | 丝杠/轴承 | 灵巧手 | 关节模组
-- =============================================================

-- 插入上游零部件企业数据
INSERT INTO companies (
    name, name_cn, slug, industry_slug, sub_sector, 
    country, hq_city, hq_province, founded_year,
    description, description_cn,
    funding_stage, funding_total_usd, valuation_usd, valuation_date,
    lead_investors, all_investors,
    founders, team_background, university_tags,
    core_products, product_status, unit_shipment, unit_price_usd,
    tech_route, tech_maturity_level, world_model_score, ai_approach, patent_count,
    supply_chain_tier, ecosystem_position, key_components,
    primary_use_cases, customer_breakdown, key_partners,
    data_sources, data_reliability, notes,
    is_tracked, is_public, status, created_at, updated_at
) VALUES 

-- ============================================
-- 一、减速器（Harmonic Drive / Planetary / RV）
-- ============================================

-- 1. 绿的谐波（已上市）- 谐波减速器龙头
(
    'Leader Harmonious Drive', '绿的谐波', 'leader-harmonic-drive', 'manufacturing', 'robotics-component',
    'CN', 'Suzhou', 'Jiangsu', 2011,
    'China''s leading harmonic drive manufacturer. Core supplier for humanoid robot joint actuators. Listed on STAR Market.',
    '中国谐波减速器龙头，人形机器人关节核心供应商。科创板上市。',
    'ipo', 
    100000000, 
    800000000, 
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO', 'Sequoia China'],
    ARRAY['Zuo Xingguo'],
    'Founded by Zuo Xingguo, Shanghai Jiao Tong University background. Pioneer in domestic harmonic drive technology.',
    ARRAY['SJTU'],
    ARRAY['Harmonic Drive HD-14', 'HD-17', 'HD-20', 'HD-25', 'HD-32'], 
    'mass_production', 
    500000, 
    2000,
    'Self-developed harmonic drive with 3S tooth profile. Achieved import substitution for Japanese HD Systems.',
    8, NULL, NULL, 
    150,
    'upstream', 
    'Domestic harmonic drive leader with 25%+ market share in China. Key supplier for UBTECH, Unitree, and other humanoid OEMs.',
    ARRAY['harmonic drive', 'wave generator', 'flexspline', 'circular spline'],
    ARRAY['humanoid robot', 'industrial robot', 'collaborative robot', 'medical robot'],
    '{"humanoid_robot": 30, "industrial_robot": 40, "collaborative_robot": 20, "other": 10}'::jsonb,
    ARRAY['UBTECH', 'Unitree', 'Estun', 'Inovance', 'STEP'],
    ARRAY['STAR Market Filing', 'Company Annual Report', 'Industry Reports'],
    'S',
    'Listed on STAR Market (688017.SH). Revenue ~300M RMB in 2024. Gross margin ~40%. Main competitor to Japanese HD Systems and Harmonic Drive Systems.',
    true, true, 'active', NOW(), NOW()
),

-- 2. 来福谐波 - 谐波减速器
(
    'Laifute Harmonic', '来福谐波', 'laifute-harmonic', 'manufacturing', 'robotics-component',
    'CN', 'Ningbo', 'Zhejiang', 2013,
    'Harmonic drive manufacturer focusing on miniaturization and high-precision applications.',
    '专注于小型化和高精度应用的谐波减速器制造商。',
    'series-b',
    30000000,
    150000000,
    '2023-06',
    ARRAY['Sequoia China', 'Shunwei Capital'],
    ARRAY['Sequoia China', 'Shunwei Capital', 'Qianhai Fund'],
    NULL,
    'Ningbo-based harmonic drive specialist. Focus on compact designs for humanoid robots.',
    ARRAY[],
    ARRAY['LCS Series', 'LCSG Series', 'LCD Series'],
    'mass_production',
    100000,
    1500,
    'Compact harmonic drive design for space-constrained humanoid joints.',
    7, NULL, NULL,
    80,
    'upstream',
    'Mid-tier harmonic drive supplier. Strong in compact designs for humanoid applications.',
    ARRAY['harmonic drive', 'compact reducer'],
    ARRAY['humanoid robot', 'collaborative robot', 'medical device'],
    '{"humanoid_robot": 40, "collaborative_robot": 35, "medical": 25}'::jsonb,
    ARRAY['Multiple humanoid OEMs'],
    ARRAY['Company Website', 'Investment Announcements'],
    'B',
    'Series B funded. Estimated annual capacity 100K+ units. Focus on miniaturization for humanoid joints.',
    true, false, 'active', NOW(), NOW()
),

-- 3. 大族传动 - 谐波/行星减速器
(
    'Han''s Motion', '大族传动', 'hans-motion', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2015,
    'Subsidiary of Han''s Laser. Produces harmonic and planetary reducers for robotics.',
    '大族激光子公司，生产谐波和行星减速器。',
    'undisclosed',
    0,
    NULL,
    NULL,
    ARRAY['Han's Laser'],
    ARRAY['Han's Laser'],
    NULL,
    'Backed by Han''s Laser (002008.SZ), leveraging manufacturing expertise.',
    ARRAY[],
    ARRAY['Harmonic Reducer', 'Planetary Reducer'],
    'mass_production',
    50000,
    1800,
    'Leverages Han''s Laser manufacturing capabilities for precision reducer production.',
    7, NULL, NULL,
    50,
    'upstream',
    'Mid-tier supplier with strong parent company backing. Diversified product portfolio.',
    ARRAY['harmonic reducer', 'planetary reducer'],
    ARRAY['industrial robot', 'humanoid robot', 'automation'],
    '{"industrial_robot": 60, "humanoid_robot": 20, "other": 20}'::jsonb,
    ARRAY['Han's Laser', 'Internal use'],
    ARRAY['Parent Company Reports'],
    'B',
    'Subsidiary of listed Han''s Laser. Benefits from parent company manufacturing scale.',
    true, false, 'active', NOW(), NOW()
),

-- 4. 双环传动（已上市）- RV减速器
(
    'Shuanghuan Transmission', '双环传动', 'shuanghuan-transmission', 'manufacturing', 'robotics-component',
    'CN', 'Taizhou', 'Zhejiang', 1980,
    'Leading RV reducer manufacturer. Listed on Shenzhen Stock Exchange. Major supplier for industrial robots.',
    '领先的RV减速器制造商，深交所上市。工业机器人主要供应商。',
    'ipo',
    50000000,
    1200000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    ARRAY['Wu Changjiang'],
    'Founded by Wu Changjiang. Decades of experience in precision gear manufacturing.',
    ARRAY[],
    ARRAY['RV Reducer SHPR Series', 'RV-C Series', 'RV-E Series'],
    'mass_production',
    200000,
    3000,
    'RV reducer technology for heavy-load industrial and humanoid applications.',
    8, NULL, NULL,
    200,
    'upstream',
    'Leading RV reducer supplier in China. Strong in heavy-load applications. Expanding to humanoid market.',
    ARRAY['RV reducer', 'precision gears', 'gearbox'],
    ARRAY['industrial robot', 'humanoid robot', 'CNC machine'],
    '{"industrial_robot": 70, "CNC_machine": 20, "humanoid_robot": 10}'::jsonb,
    ARRAY['Estun', 'STEP', 'GSK'],
    ARRAY['SZSE Annual Report', 'Company Website'],
    'S',
    'Listed on SZSE (002472.SZ). Leading domestic RV reducer supplier. Revenue >5B RMB annually.',
    true, true, 'active', NOW(), NOW()
),

-- 5. 中大力德（已上市）- 行星/谐波减速器
(
    'Zhongda Leader', '中大力德', 'zhongda-leader', 'manufacturing', 'robotics-component',
    'CN', 'Ningbo', 'Zhejiang', 2006,
    'Listed manufacturer of planetary and harmonic reducers. Focus on precision motion control.',
    '行星和谐波减速器上市公司，专注于精密运动控制。',
    'ipo',
    30000000,
    600000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Ningbo-based precision reducer manufacturer with strong R&D capabilities.',
    ARRAY[],
    ARRAY['Planetary Reducer', 'Harmonic Reducer', 'Gear Motor'],
    'mass_production',
    300000,
    800,
    'Integrated reducer and motor solutions for robotics and automation.',
    7, NULL, NULL,
    100,
    'upstream',
    'Mid-tier supplier with integrated motor+reducer solutions. Cost-competitive.',
    ARRAY['planetary reducer', 'harmonic reducer', 'gear motor'],
    ARRAY['industrial robot', 'AGV', 'automation', 'humanoid robot'],
    '{"industrial_robot": 50, "AGV": 25, "automation": 20, "humanoid_robot": 5}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['SZSE Annual Report'],
    'S',
    'Listed on SZSE (002896.SZ). Integrated reducer+motor solutions. Revenue ~1B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- ============================================
-- 二、电机/执行器（Motor / Actuator）
-- ============================================

-- 6. 汇川技术（已上市）- 伺服电机/驱动
(
    'Inovance', '汇川技术', 'inovance', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2003,
    'China''s leading industrial automation company. Core supplier of servo motors and drives for humanoid robots.',
    '中国领先的工业自动化公司，人形机器人伺服电机和驱动核心供应商。',
    'ipo',
    200000000,
    15000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO', 'GIC'],
    ARRAY['Zhu Xingming'],
    'Founded by Zhu Xingming, Huawei background. Leading industrial automation expert in China.',
    ARRAY['Huawei'],
    ARRAY['Servo Motor SV660', 'SV680', 'Drive IS620', 'IS650', 'Linear Actuator'],
    'mass_production',
    2000000,
    500,
    'Full-stack industrial automation including servo motors, drives, PLCs. Expanding to humanoid actuators.',
    9, NULL, NULL,
    3000,
    'upstream',
    'Industrial automation leader expanding to humanoid components. Strong R&D and manufacturing scale.',
    ARRAY['servo motor', 'servo drive', 'PLC', 'linear actuator'],
    ARRAY['industrial robot', 'CNC', 'humanoid robot', 'automation'],
    '{"industrial_automation": 80, "humanoid_robot": 10, "other": 10}'::jsonb,
    ARRAY['UBTECH', 'Unitree', 'Estun', 'Efort'],
    ARRAY['SZSE Annual Report', 'Company Website'],
    'S',
    'Listed on SZSE (300124.SZ). China''s largest industrial automation company. Revenue >30B RMB. Market cap >150B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 7. 禾川科技（已上市）- 伺服电机
(
    'HCFA', '禾川科技', 'hcfa', 'manufacturing', 'robotics-component',
    'CN', 'Quzhou', 'Zhejiang', 2011,
    'Listed servo motor and drive manufacturer. Focus on industrial automation and robotics.',
    '伺服电机和驱动器上市公司，专注于工业自动化和机器人。',
    'ipo',
    50000000,
    3000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO', 'Sequoia China'],
    ARRAY['Wang Xiang'],
    'Founded by Wang Xiang. Focus on servo systems for industrial applications.',
    ARRAY[],
    ARRAY['Servo Motor X3', 'X5 Series', 'Servo Drive'],
    'mass_production',
    500000,
    400,
    'Servo motor and drive systems for industrial robots and automation.',
    8, NULL, NULL,
    500,
    'upstream',
    'Mid-tier servo supplier. Strong in cost-effective solutions for Chinese market.',
    ARRAY['servo motor', 'servo drive', 'motion controller'],
    ARRAY['industrial robot', 'CNC', 'packaging', 'humanoid robot'],
    '{"industrial_robot": 60, "CNC": 25, "other": 15}'::jsonb,
    ARRAY['Multiple robot OEMs'],
    ARRAY['STAR Market Filing'],
    'S',
    'Listed on STAR Market (688320.SH). Revenue ~1.5B RMB. Strong growth in servo market.',
    true, true, 'active', NOW(), NOW()
),

-- 8. 步科股份（已上市）- 无框力矩电机
(
    'Step Electric', '步科股份', 'step-electric', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 1996,
    'Listed manufacturer of frameless torque motors. Key supplier for robot joint actuators.',
    '无框力矩电机上市公司，机器人关节执行器关键供应商。',
    'ipo',
    40000000,
    2500000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Long history in motion control. Pioneer in frameless torque motors for robotics.',
    ARRAY[],
    ARRAY['Frameless Torque Motor', 'Servo Drive', 'Motion Controller'],
    'mass_production',
    300000,
    600,
    'Frameless torque motors specifically designed for robot joint applications.',
    8, NULL, NULL,
    400,
    'upstream',
    'Leading frameless torque motor supplier for robotics. Key component for joint actuators.',
    ARRAY['frameless torque motor', 'servo drive', 'encoder'],
    ARRAY['humanoid robot', 'collaborative robot', 'medical robot', 'AGV'],
    '{"humanoid_robot": 35, "collaborative_robot": 30, "medical_robot": 20, "AGV": 15}'::jsonb,
    ARRAY['UBTECH', 'Unitree', 'Multiple OEMs'],
    ARRAY['STAR Market Annual Report'],
    'S',
    'Listed on STAR Market (688160.SH). Leading frameless torque motor supplier. Revenue ~500M RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 9. 鸣志电器（已上市）- 步进/伺服电机
(
    'Moons'' Electric', '鸣志电器', 'moons-electric', 'manufacturing', 'robotics-component',
    'CN', 'Shanghai', 'Shanghai', 1994,
    'Leading stepper and servo motor manufacturer. Listed on Shanghai Stock Exchange.',
    '领先的步进和伺服电机制造商，上交所上市。',
    'ipo',
    60000000,
    8000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    ARRAY['Chang Jianming'],
    'Founded by Chang Jianming. Leading motion control company with global presence.',
    ARRAY[],
    ARRAY['Stepper Motor', 'Servo Motor', 'Brushless DC Motor', 'Linear Actuator'],
    'mass_production',
    10000000,
    300,
    'Comprehensive motor portfolio including stepper, servo, and linear actuators.',
    8, NULL, NULL,
    800,
    'upstream',
    'Leading motor manufacturer with global reach. Strong in precision motion control.',
    ARRAY['stepper motor', 'servo motor', 'BLDC motor', 'linear actuator'],
    ARRAY['industrial automation', 'robotics', 'medical', '3D printing'],
    '{"industrial_automation": 50, "robotics": 25, "medical": 15, "other": 10}'::jsonb,
    ARRAY['Global robotics OEMs'],
    ARRAY['SSE Annual Report'],
    'S',
    'Listed on SSE (603728.SH). Global motor supplier. Revenue >3B RMB. Strong international presence.',
    true, true, 'active', NOW(), NOW()
),

-- 10. 江苏雷利（已上市）- 微型电机
(
    'Jiangsu Leili', '江苏雷利', 'jiangsu-leili', 'manufacturing', 'robotics-component',
    'CN', 'Changzhou', 'Jiangsu', 2006,
    'Listed micro motor manufacturer. Expanding to robot actuator market.',
    '微型电机上市公司，拓展机器人执行器市场。',
    'ipo',
    80000000,
    5000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Changzhou-based micro motor specialist. Strong in precision small motors.',
    ARRAY[],
    ARRAY['Micro Motor', 'Linear Actuator', 'Gear Motor'],
    'mass_production',
    5000000,
    200,
    'Micro motors and linear actuators for robotics and automation.',
    7, NULL, NULL,
    300,
    'upstream',
    'Leading micro motor supplier. Expanding to robot actuator applications.',
    ARRAY['micro motor', 'linear actuator', 'gear motor'],
    ARRAY['home appliance', 'automotive', 'robotics', 'medical'],
    '{"home_appliance": 50, "automotive": 25, "robotics": 15, "medical": 10}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['SZSE Annual Report'],
    'S',
    'Listed on SZSE (300660.SZ). Leading micro motor supplier. Revenue >3B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- ============================================
-- 三、传感器（视觉/力觉/IMU）
-- ============================================

-- 11. 奥比中光（已上市）- 3D视觉传感器
(
    'Orbbec', '奥比中光', 'orbbec', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2013,
    'Leading 3D vision sensor company. Listed on STAR Market. Key supplier for robot perception.',
    '领先的3D视觉传感器公司，科创板上市。机器人感知关键供应商。',
    'ipo',
    200000000,
    8000000000,
    '2024-12',
    ARRAY['IPO', 'Ant Group'],
    ARRAY['IPO', 'Ant Group', 'Saif Partners', 'Legend Capital'],
    ARRAY['Huang Yuanhao'],
    'Founded by Huang Yuanhao. Pioneer in domestic 3D structured light technology.',
    ARRAY['SJTU'],
    ARRAY['Femto Bolt', 'Femto Mega', 'Astra Series', 'Gemini Series'],
    'mass_production',
    2000000,
    800,
    '3D structured light and ToF sensors for robot vision. Apple Face ID supplier ecosystem.',
    8, NULL, NULL,
    600,
    'upstream',
    'Leading 3D vision sensor supplier. Key perception component for humanoid robots.',
    ARRAY['3D structured light', 'ToF sensor', 'depth camera', 'vision algorithm'],
    ARRAY['humanoid robot', 'service robot', 'industrial robot', 'face recognition'],
    '{"humanoid_robot": 25, "service_robot": 35, "industrial_robot": 20, "face_recognition": 20}'::jsonb,
    ARRAY['UBTECH', 'Unitree', 'AgiBot', 'Multiple OEMs'],
    ARRAY['STAR Market Filing', 'Company Website'],
    'S',
    'Listed on STAR Market (688322.SH). Leading 3D vision company. Revenue ~500M RMB. Strong in structured light.',
    true, true, 'active', NOW(), NOW()
),

-- 12. 速腾聚创（已上市）- 激光雷达
(
    'RoboSense', '速腾聚创', 'robosense', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2014,
    'Leading LiDAR manufacturer. Listed on Hong Kong Stock Exchange. Key for robot navigation.',
    '领先的激光雷达制造商，港交所上市。机器人导航关键供应商。',
    'ipo',
    300000000,
    12000000000,
    '2024-12',
    ARRAY['IPO', 'Cainiao', 'BYD'],
    ARRAY['IPO', 'Cainiao', 'BYD', 'NIO Capital', 'Porsche Ventures'],
    ARRAY['Qiu Chunxin'],
    'Founded by Qiu Chunxin. Leading LiDAR technology for autonomous vehicles and robots.',
    ARRAY['HIT'],
    ARRAY['M Series', 'E Series', 'Helios', 'Bpearl'],
    'mass_production',
    500000,
    3000,
    'MEMS and mechanical LiDAR for autonomous driving and robotics applications.',
    8, NULL, NULL,
    800,
    'upstream',
    'Leading LiDAR supplier. Expanding from automotive to robotics applications.',
    ARRAY['LiDAR', 'MEMS mirror', 'perception software'],
    ARRAY['autonomous_vehicle': 70, 'robotics': 20, 'industrial': 10}'::jsonb,
    ARRAY['NIO', 'XPeng', 'Li Auto', 'BYD'],
    ARRAY['HKEX Filing', 'Company Website'],
    'S',
    'Listed on HKEX (02498.HK). Leading LiDAR supplier. Shipped 500K+ units in 2024.',
    true, true, 'active', NOW(), NOW()
),

-- 13. 禾赛科技（已上市）- 激光雷达
(
    'Hesai', '禾赛科技', 'hesai', 'manufacturing', 'robotics-component',
    'CN', 'Shanghai', 'Shanghai', 2014,
    'Leading LiDAR manufacturer. Listed on NASDAQ. Strong in high-performance LiDAR.',
    '领先的激光雷达制造商，纳斯达克上市。高性能激光雷达领域强势。',
    'ipo',
    400000000,
    15000000000,
    '2024-12',
    ARRAY['IPO', 'Baidu', 'Bosch'],
    ARRAY['IPO', 'Baidu', 'Bosch', 'LightSpeed', 'CPE'],
    ARRAY['Li Yifan', 'Sun Kai', 'Xiang Shaoqing'],
    'Founded by Stanford PhDs. Leading high-performance LiDAR technology.',
    ARRAY['Stanford'],
    ARRAY['AT Series', 'ET Series', 'FT Series', 'Pandar Series'],
    'mass_production',
    400000,
    5000,
    'High-performance LiDAR with proprietary ASIC chips. Strong in autonomous driving.',
    8, NULL, NULL,
    700,
    'upstream',
    'Leading high-performance LiDAR supplier. Expanding to robotics and industrial.',
    ARRAY['LiDAR', 'ASIC chip', 'optical system'],
    ARRAY['autonomous_vehicle': 75, 'robotics': 15, 'industrial': 10}'::jsonb,
    ARRAY['Li Auto', 'Jidu', 'Baidu Apollo'],
    ARRAY['NASDAQ Filing', 'Company Website'],
    'S',
    'Listed on NASDAQ (HSAI). Leading LiDAR company. Revenue >1B RMB. Strong R&D capabilities.',
    true, true, 'active', NOW(), NOW()
),

-- 14. 宇立仪器 - 六维力传感器
(
    'SRI', '宇立仪器', 'sri-instruments', 'manufacturing', 'robotics-component',
    'CN', 'Shanghai', 'Shanghai', 2007,
    'Leading 6-axis force/torque sensor manufacturer. Key supplier for robot force control.',
    '领先的六维力/力矩传感器制造商，机器人力控关键供应商。',
    'undisclosed',
    20000000,
    200000000,
    '2023-12',
    ARRAY['Sequoia China', 'Hillhouse Capital'],
    ARRAY['Sequoia China', 'Hillhouse Capital'],
    NULL,
    'Shanghai-based force sensor specialist. Strong in 6-axis force/torque sensors.',
    ARRAY['SJTU'],
    ARRAY['6-Axis Force Sensor', 'Torque Sensor', 'Force Control System'],
    'mass_production',
    50000,
    5000,
    '6-axis force/torque sensors for robot force control and humanoid applications.',
    7, NULL, NULL,
    100,
    'upstream',
    'Leading force sensor supplier for robotics. Critical for humanoid force control.',
    ARRAY['6-axis force sensor', 'torque sensor', 'force control algorithm'],
    ARRAY['humanoid robot', 'industrial robot', 'medical robot', 'research'],
    '{"humanoid_robot": 40, "industrial_robot": 30, "medical_robot": 20, "research": 10}'::jsonb,
    ARRAY['UBTECH', 'Unitree', 'AgiBot'],
    ARRAY['Company Website', 'Investment Announcements'],
    'B',
    'Leading domestic force sensor supplier. Critical component for humanoid robot force control.',
    true, false, 'active', NOW(), NOW()
),

-- 15. 柯力传感（已上市）- 力传感器
(
    'Keli Sensing', '柯力传感', 'keli-sensing', 'manufacturing', 'robotics-component',
    'CN', 'Ningbo', 'Zhejiang', 1995,
    'Listed force sensor manufacturer. Expanding to robot force control applications.',
    '力传感器上市公司，拓展机器人力控应用。',
    'ipo',
    100000000,
    6000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    ARRAY['Ke Jian'],
    'Leading force sensor manufacturer with decades of experience.',
    ARRAY[],
    ARRAY['Force Sensor', 'Torque Sensor', 'Weighing System'],
    'mass_production',
    2000000,
    500,
    'Force and torque sensors for industrial and robotics applications.',
    7, NULL, NULL,
    300,
    'upstream',
    'Leading force sensor supplier. Expanding to robotics and humanoid applications.',
    ARRAY['force sensor', 'torque sensor', 'weighing sensor'],
    ARRAY['industrial': 70, 'robotics': 20, 'other': 10}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['SSE Annual Report'],
    'S',
    'Listed on SSE (603662.SH). Leading force sensor company. Revenue >1B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 16. 芯动联科（已上市）- IMU传感器
(
    'Xindong Technology', '芯动联科', 'xindong-tech', 'manufacturing', 'robotics-component',
    'CN', 'Wuxi', 'Jiangsu', 2012,
    'Listed MEMS IMU sensor manufacturer. Key for robot balance and navigation.',
    'MEMS IMU传感器上市公司，机器人平衡和导航关键供应商。',
    'ipo',
    30000000,
    4000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO', 'Sequoia China'],
    NULL,
    'Wuxi-based MEMS sensor specialist. Strong in IMU for robotics.',
    ARRAY[],
    ARRAY['MEMS IMU', 'Gyroscope', 'Accelerometer'],
    'mass_production',
    1000000,
    300,
    'High-performance MEMS IMU for robot balance control and navigation.',
    7, NULL, NULL,
    200,
    'upstream',
    'Leading MEMS IMU supplier. Critical for humanoid robot balance control.',
    ARRAY['MEMS IMU', 'gyroscope', 'accelerometer'],
    ARRAY['robotics': 30, 'automotive': 40, 'industrial': 20, 'consumer': 10}'::jsonb,
    ARRAY['Multiple robot OEMs'],
    ARRAY['STAR Market Filing'],
    'S',
    'Listed on STAR Market. Leading MEMS IMU supplier. Strong growth in robotics.',
    true, true, 'active', NOW(), NOW()
),

-- ============================================
-- 四、丝杠/轴承（Ball Screw / Bearing）
-- ============================================

-- 17. 鼎智科技（已上市）- 微型丝杠
(
    'Dingzhi Tech', '鼎智科技', 'dingzhi-tech', 'manufacturing', 'robotics-component',
    'CN', 'Changzhou', 'Jiangsu', 2008,
    'Listed micro ball screw manufacturer. Key supplier for robot linear actuators.',
    '微型滚珠丝杠上市公司，机器人线性执行器关键供应商。',
    'ipo',
    20000000,
    2000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Changzhou-based precision ball screw specialist.',
    ARRAY[],
    ARRAY['Micro Ball Screw', 'Linear Actuator', 'Stepper Motor'],
    'mass_production',
    500000,
    600,
    'Micro ball screws for robot linear joints and precision applications.',
    7, NULL, NULL,
    150,
    'upstream',
    'Leading micro ball screw supplier. Key component for humanoid linear actuators.',
    ARRAY['micro ball screw', 'linear actuator', 'stepper motor'],
    ARRAY['humanoid robot': 30, 'medical': 25, 'industrial': 25, 'automotive': 20}'::jsonb,
    ARRAY['Tesla Bot', 'Multiple OEMs'],
    ARRAY['STAR Market Filing'],
    'S',
    'Listed on STAR Market. Leading micro ball screw supplier. Tesla Bot supply chain.',
    true, true, 'active', NOW(), NOW()
),

-- 18. 贝斯特（已上市）- 精密丝杠
(
    'Best Precision', '贝斯特', 'best-precision', 'manufacturing', 'robotics-component',
    'CN', 'Wuxi', 'Jiangsu', 1997,
    'Listed precision ball screw manufacturer. Expanding to robot applications.',
    '精密滚珠丝杠上市公司，拓展机器人应用。',
    'ipo',
    50000000,
    8000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Wuxi-based precision mechanical components manufacturer.',
    ARRAY[],
    ARRAY['Ball Screw', 'Linear Guide', 'Precision Component'],
    'mass_production',
    2000000,
    800,
    'Precision ball screws for industrial and robotics applications.',
    7, NULL, NULL,
    200,
    'upstream',
    'Leading precision component supplier. Expanding to humanoid robot market.',
    ARRAY['ball screw', 'linear guide', 'precision component'],
    ARRAY['automotive': 50, 'industrial': 30, 'robotics': 20}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['SZSE Annual Report'],
    'S',
    'Listed on SZSE. Precision component manufacturer. Revenue >1B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 19. 五洲新春（已上市）- 轴承/丝杠
(
    'Xinchun Bearing', '五洲新春', 'xinchun-bearing', 'manufacturing', 'robotics-component',
    'CN', 'Shaoxing', 'Zhejiang', 1999,
    'Listed bearing and ball screw manufacturer. Key supplier for robot joints.',
    '轴承和滚珠丝杠上市公司，机器人关节关键供应商。',
    'ipo',
    40000000,
    5000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Shaoxing-based bearing and precision components manufacturer.',
    ARRAY[],
    ARRAY['Ball Bearing', 'Roller Bearing', 'Ball Screw'],
    'mass_production',
    5000000,
    200,
    'Bearings and ball screws for automotive, industrial, and robotics.',
    7, NULL, NULL,
    300,
    'upstream',
    'Leading bearing supplier. Expanding to robot joint and linear actuator market.',
    ARRAY['ball bearing', 'roller bearing', 'ball screw'],
    ARRAY['automotive': 60, 'industrial': 25, 'robotics': 15}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['SSE Annual Report'],
    'S',
    'Listed on SSE. Leading bearing manufacturer. Revenue >3B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 20. 秦川机床（已上市）- 滚珠丝杠
(
    'Qinchuan Machine Tool', '秦川机床', 'qinchuan-machine', 'manufacturing', 'robotics-component',
    'CN', 'Baoji', 'Shaanxi', 1965,
    'State-owned machine tool manufacturer. Produces ball screws for industrial applications.',
    '国有机床制造商，生产工业用滚珠丝杠。',
    'ipo',
    100000000,
    8000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'State-owned enterprise with long history in machine tools and precision components.',
    ARRAY[],
    ARRAY['Ball Screw', 'CNC Machine', 'Gear'],
    'mass_production',
    1000000,
    1000,
    'Ball screws and machine tools for industrial applications.',
    7, NULL, NULL,
    500,
    'upstream',
    'State-owned precision component supplier. Strong in heavy industrial applications.',
    ARRAY['ball screw', 'CNC machine', 'gear'],
    ARRAY['industrial': 80, 'automotive': 15, 'robotics': 5}'::jsonb,
    ARRAY['State-owned enterprises'],
    ARRAY['SZSE Annual Report'],
    'S',
    'Listed on SZSE. State-owned machine tool manufacturer. Revenue >4B RMB.',
    true, true, 'active', NOW(), NOW()
),

-- ============================================
-- 五、灵巧手（Dexterous Hand）
-- ============================================

-- 21. 因时机器人 - 微型伺服电缸/灵巧手
(
    'Instime Robotics', '因时机器人', 'instime-robotics', 'manufacturing', 'robotics-component',
    'CN', 'Beijing', 'Beijing', 2016,
    'Leading micro servo actuator and dexterous hand manufacturer.',
    '领先的微型伺服电缸和灵巧手制造商。',
    'series-b',
    40000000,
    300000000,
    '2024-06',
    ARRAY['Sequoia China', 'Hillhouse Capital'],
    ARRAY['Sequoia China', 'Hillhouse Capital', 'Source Code Capital'],
    NULL,
    'Beijing-based micro actuator specialist. Pioneer in compact servo actuators.',
    ARRAY['Tsinghua'],
    ARRAY['Micro Servo Actuator', 'RH56DFX Series', 'Dexterous Hand'],
    'mass_production',
    100000,
    3000,
    'Micro servo actuators for robot joints and dexterous hands.',
    7, NULL, NULL,
    80,
    'upstream',
    'Leading micro actuator supplier. Key component for humanoid dexterous hands.',
    ARRAY['micro servo actuator', 'dexterous hand', 'compact joint'],
    ARRAY['humanoid robot': 50, 'prosthetic': 25, 'research': 25}'::jsonb,
    ARRAY['UBTECH', 'Unitree', 'AgiBot'],
    ARRAY['Company Website', 'Investment Announcements'],
    'B',
    'Leading micro actuator supplier. Key for humanoid dexterous hands. Series B funded.',
    true, false, 'active', NOW(), NOW()
),

-- 22. 帕西尼感知 - 触觉传感器/灵巧手
(
    'Paxini', '帕西尼感知', 'paxini', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2021,
    'Tactile sensor and dexterous hand manufacturer. Focus on high-DOF hands.',
    '触觉传感器和灵巧手制造商，专注于高自由度灵巧手。',
    'series-a',
    20000000,
    150000000,
    '2024-03',
    ARRAY['Sequoia China Seed Fund', 'ZhenFund'],
    ARRAY['Sequoia China Seed Fund', 'ZhenFund', 'MiraclePlus'],
    NULL,
    'Shenzhen-based tactile sensor and dexterous hand startup.',
    ARRAY[],
    ARRAY['Tactile Sensor', 'Dexterous Hand', 'Haptic Feedback'],
    'pilot_production',
    1000,
    15000,
    'High-DOF dexterous hands with integrated tactile sensing.',
    6, NULL, NULL,
    30,
    'upstream',
    'Innovative dexterous hand startup. Focus on tactile sensing integration.',
    ARRAY['tactile sensor', 'dexterous hand', 'haptic feedback'],
    ARRAY['humanoid robot': 60, 'research': 30, 'prosthetic': 10}'::jsonb,
    ARRAY['Multiple humanoid OEMs'],
    ARRAY['Company Website', 'Investment Announcements'],
    'C',
    'Early stage dexterous hand company. Focus on tactile sensing. Series A.',
    true, false, 'active', NOW(), NOW()
),

-- 23. 灵心巧手 - 灵巧手
(
    'Lingxin Dexhand', '灵心巧手', 'lingxin-dexhand', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2022,
    'Dexterous hand manufacturer. Focus on affordable high-DOF hands.',
    '灵巧手制造商，专注于高性价比高自由度灵巧手。',
    'angel',
    10000000,
    80000000,
    '2024-01',
    ARRAY['ZhenFund', 'MiraclePlus'],
    ARRAY['ZhenFund', 'MiraclePlus'],
    NULL,
    'Shenzhen-based dexterous hand startup. Focus on cost-effective solutions.',
    ARRAY[],
    ARRAY['Dexterous Hand', 'Robot Gripper'],
    'pilot_production',
    500,
    8000,
    'Affordable dexterous hands for humanoid robots.',
    5, NULL, NULL,
    20,
    'upstream',
    'Early stage dexterous hand supplier. Focus on cost reduction.',
    ARRAY['dexterous hand', 'robot gripper'],
    ARRAY['humanoid robot': 70, 'research': 30}'::jsonb,
    ARRAY['Multiple startups'],
    ARRAY['Company Website'],
    'C',
    'Early stage dexterous hand company. Focus on affordability. Angel funded.',
    true, false, 'active', NOW(), NOW()
),

-- ============================================
-- 六、关节模组/执行器（Joint Module / Actuator）
-- ============================================

-- 24. 智同科技 - 精密减速器+关节模组
(
    'Zhitong Tech', '智同科技', 'zhitong-tech', 'manufacturing', 'robotics-component',
    'CN', 'Beijing', 'Beijing', 2015,
    'Precision reducer and joint module manufacturer. Focus on robot joint integration.',
    '精密减速器和关节模组制造商，专注于机器人关节集成。',
    'series-b',
    50000000,
    400000000,
    '2023-12',
    ARRAY['Sequoia China', 'Hillhouse Capital'],
    ARRAY['Sequoia China', 'Hillhouse Capital', 'Source Code Capital'],
    NULL,
    'Beijing-based joint module specialist. Focus on integrated actuator solutions.',
    ARRAY['Tsinghua'],
    ARRAY['Joint Module', 'Integrated Actuator', 'Harmonic Drive'],
    'mass_production',
    50000,
    5000,
    'Integrated joint modules combining motor, reducer, and controller.',
    7, NULL, NULL,
    100,
    'upstream',
    'Joint module integrator. Provides complete actuator solutions for robot OEMs.',
    ARRAY['joint module', 'integrated actuator', 'harmonic drive'],
    ARRAY['humanoid robot': 40, 'collaborative_robot': 35, 'industrial_robot': 25}'::jsonb,
    ARRAY['Multiple robot OEMs'],
    ARRAY['Company Website', 'Investment Announcements'],
    'B',
    'Joint module supplier. Provides integrated actuator solutions. Series B.',
    true, false, 'active', NOW(), NOW()
),

-- 25. 本末科技 - 直驱电机/关节模组
(
    'DirectDrive Tech', '本末科技', 'directdrive-tech', 'manufacturing', 'robotics-component',
    'CN', 'Dongguan', 'Guangdong', 2018,
    'Direct drive motor and joint module manufacturer. Focus on high-torque density.',
    '直驱电机和关节模组制造商，专注于高扭矩密度。',
    'series-a',
    20000000,
    150000000,
    '2024-03',
    ARRAY['Sequoia China Seed Fund', 'ZhenFund'],
    ARRAY['Sequoia China Seed Fund', 'ZhenFund', 'MiraclePlus'],
    NULL,
    'Dongguan-based direct drive motor specialist.',
    ARRAY[],
    ARRAY['Direct Drive Motor', 'Joint Module', 'High-Torque Actuator'],
    'pilot_production',
    20000,
    4000,
    'Direct drive motors for high-precision robot joints.',
    6, NULL, NULL,
    50,
    'upstream',
    'Direct drive motor supplier. Alternative to reducer-based joints.',
    ARRAY['direct drive motor', 'joint module', 'high-torque actuator'],
    ARRAY['humanoid robot': 30, 'collaborative_robot': 40, 'medical_robot': 30}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['Company Website'],
    'C',
    'Direct drive motor supplier. Alternative approach to robot joints. Series A.',
    true, false, 'active', NOW(), NOW()
),

-- 26. 威洛博机器人 - 线性模组
(
    'Wellpo Robot', '威洛博机器人', 'wellpo-robot', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2011,
    'Linear module and actuator manufacturer. Focus on precision linear motion.',
    '线性模组和执行器制造商，专注于精密线性运动。',
    'undisclosed',
    10000000,
    100000000,
    '2023-12',
    ARRAY['Shenzhen Capital Group'],
    ARRAY['Shenzhen Capital Group'],
    NULL,
    'Shenzhen-based linear motion specialist.',
    ARRAY[],
    ARRAY['Linear Module', 'Linear Actuator', 'Cartesian Robot'],
    'mass_production',
    100000,
    2000,
    'Linear modules for automation and robotics applications.',
    7, NULL, NULL,
    60,
    'upstream',
    'Linear module supplier. Used in robot linear joints and automation.',
    ARRAY['linear module', 'linear actuator', 'Cartesian robot'],
    ARRAY['automation': 70, 'robotics': 20, 'other': 10}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['Company Website'],
    'B',
    'Linear module manufacturer. Used in robot linear actuators.',
    true, false, 'active', NOW(), NOW()
),

-- ============================================
-- 七、其他核心零部件
-- ============================================

-- 27. 同川科技 - 谐波减速器
(
    'Tongchuan Tech', '同川科技', 'tongchuan-tech', 'manufacturing', 'robotics-component',
    'CN', 'Shenzhen', 'Guangdong', 2012,
    'Harmonic drive manufacturer. Focus on cost-effective reducers for robotics.',
    '谐波减速器制造商，专注于高性价比机器人减速器。',
    'series-a',
    15000000,
    100000000,
    '2023-06',
    ARRAY['Shenzhen Capital Group'],
    ARRAY['Shenzhen Capital Group', 'Qianhai Fund'],
    NULL,
    'Shenzhen-based harmonic drive supplier.',
    ARRAY[],
    ARRAY['Harmonic Drive', 'Planetary Reducer'],
    'mass_production',
    80000,
    1200,
    'Cost-effective harmonic drives for robotics market.',
    6, NULL, NULL,
    40,
    'upstream',
    'Mid-tier harmonic drive supplier. Focus on cost competitiveness.',
    ARRAY['harmonic drive', 'planetary reducer'],
    ARRAY['industrial_robot': 50, 'humanoid_robot': 20, 'other': 30}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['Company Website'],
    'B',
    'Harmonic drive supplier. Cost-competitive positioning. Series A.',
    true, false, 'active', NOW(), NOW()
),

-- 28. 丰立智能（已上市）- 小模数齿轮
(
    'Fengli Intelligent', '丰立智能', 'fengli-intelligent', 'manufacturing', 'robotics-component',
    'CN', 'Taizhou', 'Zhejiang', 1995,
    'Listed small module gear manufacturer. Key supplier for robot gearboxes.',
    '小模数齿轮上市公司，机器人减速器关键供应商。',
    'ipo',
    30000000,
    4000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Taizhou-based precision gear manufacturer.',
    ARRAY[],
    ARRAY['Small Module Gear', 'Gearbox', 'Precision Component'],
    'mass_production',
    5000000,
    100,
    'Small module gears for robot gearboxes and precision applications.',
    7, NULL, NULL,
    150,
    'upstream',
    'Leading small gear supplier. Key component for reducers.',
    ARRAY['small module gear', 'gearbox', 'precision component'],
    ARRAY['automotive': 40, 'industrial': 30, 'robotics': 20, 'other': 10}'::jsonb,
    ARRAY['Multiple reducer manufacturers'],
    ARRAY['SZSE Annual Report'],
    'S',
    'Listed on SZSE. Small module gear specialist. Revenue ~500M RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 29. 恒工精密（已上市）- 精密机加工
(
    'Henggong Precision', '恒工精密', 'henggong-precision', 'manufacturing', 'robotics-component',
    'CN', 'Handan', 'Hebei', 2012,
    'Listed precision machining manufacturer. Supplier for robot components.',
    '精密机加工上市公司，机器人零部件供应商。',
    'ipo',
    20000000,
    3000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Hebei-based precision machining specialist.',
    ARRAY[],
    ARRAY['Precision Machining', 'Mechanical Component', 'Hydraulic Part'],
    'mass_production',
    2000000,
    500,
    'Precision machined components for industrial and robotics.',
    7, NULL, NULL,
    100,
    'upstream',
    'Precision machining supplier. Provides components for robot actuators.',
    ARRAY['precision machining', 'mechanical component', 'hydraulic part'],
    ARRAY['industrial': 60, 'automotive': 25, 'robotics': 15}'::jsonb,
    ARRAY['Multiple OEMs'],
    ARRAY['SZSE Annual Report'],
    'S',
    'Listed on SZSE. Precision machining supplier. Revenue ~800M RMB.',
    true, true, 'active', NOW(), NOW()
),

-- 30. 北特科技（已上市）- 精密加工
(
    'Beite Technology', '北特科技', 'beite-tech', 'manufacturing', 'robotics-component',
    'CN', 'Shanghai', 'Shanghai', 2002,
    'Listed precision machining company. Expanding to robot component market.',
    '精密加工上市公司，拓展机器人零部件市场。',
    'ipo',
    50000000,
    6000000000,
    '2024-12',
    ARRAY['IPO'],
    ARRAY['IPO'],
    NULL,
    'Shanghai-based precision machining company.',
    ARRAY[],
    ARRAY['Precision Machining', 'Auto Parts', 'Robot Component'],
    'mass_production',
    5000000,
    300,
    'Precision machining for automotive and expanding to robotics.',
    7, NULL, NULL,
    200,
    'upstream',
    'Precision machining supplier. Expanding to robot component market.',
    ARRAY['precision machining', 'auto parts', 'robot component'],
    ARRAY['automotive': 70, 'robotics': 20, 'other': 10}'::jsonb,
    ARRAY['Tesla', 'Multiple OEMs'],
    ARRAY['SSE Annual Report'],
    'S',
    'Listed on SSE. Precision machining company. Revenue >1.5B RMB. Tesla supplier.',
    true, true, 'active', NOW(), NOW()
);

-- ============================================
-- 数据验证查询
-- ============================================
SELECT 
    name_cn,
    supply_chain_tier,
    funding_stage,
    funding_total_usd / 1000000 as funding_m_usd,
    unit_shipment,
    data_reliability
FROM companies 
WHERE industry_slug = 'manufacturing' AND sub_sector = 'robotics-component'
ORDER BY 
    CASE supply_chain_tier
        WHEN 'upstream' THEN 1
        WHEN 'midstream' THEN 2
        WHEN 'downstream' THEN 3
    END,
    unit_shipment DESC NULLS LAST;
