$pat = "sbp_2d9e51cc04f38bb94e7b1394ed8c1d064126a8cc"
$proj = "jqppcuccqkxhhrvndsil"
$api  = "https://api.supabase.com/v1/projects/$proj/database/query"

function Invoke-SQL($sql) {
  $body = [System.Text.Encoding]::UTF8.GetBytes("{`"query`": `"$sql`"}")
  try {
    $resp = Invoke-WebRequest -Uri $api -Method POST `
      -Headers @{ Authorization = "Bearer $pat"; "Content-Type" = "application/json" } `
      -Body $body -UseBasicParsing -TimeoutSec 20
    Write-Host "OK ($($resp.StatusCode)): $sql" -ForegroundColor Green
  } catch {
    Write-Host "ERR: $($_.Exception.Message) | SQL: $sql" -ForegroundColor Red
  }
}

Write-Host "=== Step 1: Create news table ===" -ForegroundColor Cyan

Invoke-SQL "CREATE TABLE IF NOT EXISTS news (id BIGSERIAL PRIMARY KEY, title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, summary TEXT, content TEXT, source_url TEXT, source_name TEXT, author TEXT, cover_image_url TEXT, industry_slug TEXT NOT NULL DEFAULT 'ai', company_id BIGINT, company_ids BIGINT[] DEFAULT '{}', tags TEXT[] DEFAULT '{}', is_premium BOOLEAN NOT NULL DEFAULT FALSE, is_published BOOLEAN NOT NULL DEFAULT FALSE, published_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())"

Invoke-SQL "CREATE INDEX IF NOT EXISTS idx_news_industry_slug ON news(industry_slug)"
Invoke-SQL "CREATE INDEX IF NOT EXISTS idx_news_published_at ON news(published_at DESC)"
Invoke-SQL "CREATE INDEX IF NOT EXISTS idx_news_is_published ON news(is_published)"
Invoke-SQL "CREATE INDEX IF NOT EXISTS idx_news_slug ON news(slug)"
Invoke-SQL "CREATE INDEX IF NOT EXISTS idx_news_tags ON news USING GIN(tags)"

Invoke-SQL "ALTER TABLE news ENABLE ROW LEVEL SECURITY"

Invoke-SQL "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='news' AND policyname='Public can read published news') THEN CREATE POLICY \"Public can read published news\" ON news FOR SELECT USING (is_published = true); END IF; END \$\$"
Invoke-SQL "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='news' AND policyname='Service role full access') THEN CREATE POLICY \"Service role full access\" ON news FOR ALL USING (auth.role() = 'service_role'); END IF; END \$\$"

Write-Host ""
Write-Host "=== Step 2: Insert test news data ===" -ForegroundColor Cyan

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('DeepSeek R2 Set to Challenge OpenAI o3 with 10x Cost Efficiency', 'deepseek-r2-challenge-openai-o3-cost-efficiency', 'DeepSeek is preparing its R2 model release, which industry insiders say achieves performance parity with OpenAI o3 at a fraction of the inference cost, potentially reshaping enterprise AI adoption economics.', 'DeepSeek has quietly completed internal benchmarking of its upcoming R2 model, and the results are turning heads across the AI industry. According to sources familiar with the matter, R2 demonstrates reasoning capabilities on par with OpenAI o3 on standard benchmarks including MMLU, MATH-500, and HumanEval, while operating at approximately one-tenth the inference cost.\n\nThe cost efficiency stems from DeepSeek''s mixture-of-experts architecture, which activates only a subset of parameters for any given query. This approach dramatically reduces compute requirements without sacrificing output quality.\n\nFor enterprises evaluating AI infrastructure costs, this development is significant. Many Fortune 500 companies have been holding back large-scale AI deployments due to per-query costs at scale. A model offering comparable quality at 10x lower cost could accelerate adoption timelines considerably.\n\nOpenAI has not commented on the benchmarks, but the company is expected to release o4 before DeepSeek R2 reaches general availability. The competitive dynamic between US and Chinese AI labs continues to intensify.', 'https://techcrunch.com/2026/03/deepseek-r2', 'TechCrunch', 'Sarah Chen', 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80', 'ai', ARRAY['LLM','Cost Efficiency','Enterprise AI','DeepSeek'], FALSE, TRUE, NOW() - INTERVAL '2 hours') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('Anthropic Secures \$4B Series E at \$61B Valuation Amid Surging Claude Enterprise Demand', 'anthropic-series-e-61b-valuation-claude-enterprise', 'Anthropic has closed a \$4 billion Series E funding round led by Google, valuing the AI safety company at \$61 billion. The raise comes as Claude''s enterprise API revenue reportedly grew 300% year-over-year.', 'Anthropic has officially closed its \$4 billion Series E funding round, cementing its position as one of the most valuable private AI companies in the world. The round was led by Google, with participation from Salesforce Ventures, Spark Capital, and several sovereign wealth funds.\n\nThe \$61 billion valuation represents a significant step up from the company''s previous \$40 billion mark set in late 2024. The jump reflects explosive growth in Claude''s enterprise adoption, with multiple sources indicating API revenue grew over 300% in 2025.\n\nKey drivers of this growth include Claude''s strong performance on coding tasks, its 200K context window that competitors have struggled to match at production quality, and Anthropic''s safety-first reputation that resonates with regulated industries like finance and healthcare.\n\nThe company plans to use the proceeds to expand its model training infrastructure and accelerate its Constitutional AI research program. Anthropic CEO Dario Amodei indicated in a blog post that the company is targeting AGI development within a five-year horizon.', 'https://www.wsj.com/tech/anthropic-funding-2026', 'Wall Street Journal', 'Michael Torres', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80', 'ai', ARRAY['Funding','Anthropic','Claude','Enterprise AI','Valuation'], TRUE, TRUE, NOW() - INTERVAL '5 hours') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('NVIDIA Blackwell Ultra GB300 Enters Mass Production, H100 Price Drop Accelerates', 'nvidia-blackwell-ultra-gb300-mass-production', 'NVIDIA has begun mass production of its GB300 Blackwell Ultra chips, with TSMC reportedly running three-shift operations to meet hyperscaler demand. Meanwhile H100 spot prices have fallen 40% year-to-date.', 'NVIDIA''s next-generation GB300 Blackwell Ultra GPU has entered full mass production at TSMC''s advanced packaging facilities in Arizona and Taiwan, marking a major milestone for the AI infrastructure build-out cycle.\n\nThe GB300 offers a 3x improvement in FP8 training throughput compared to the H100 and a 2.5x improvement in inference performance, according to NVIDIA''s published specifications. The chip also features HBM3e memory with 288GB capacity per GPU, addressing one of the key bottlenecks in large model training.\n\nAs GB300 supply ramps, H100 prices on the secondary market have declined sharply. Spot prices have fallen from approximately \$28,000 per unit in January to \$17,000 in mid-March, a 39% decline. This trend is expected to continue as H200 and GB200 supply also increases.\n\nMeta, Microsoft, Google, and Amazon have all reportedly placed GB300 orders totaling over 2 million units through 2026. The supply constraints that characterized the H100 era appear to be easing, which could broaden AI infrastructure access to mid-market companies that previously found the economics prohibitive.', 'https://semianalysis.com/nvidia-gb300-production', 'SemiAnalysis', 'Dylan Patel', 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80', 'semiconductor', ARRAY['NVIDIA','Blackwell','GPU','AI Infrastructure','TSMC'], FALSE, TRUE, NOW() - INTERVAL '1 day') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('ByteDance Doubao Model Surpasses 100M Daily Active Users in China', 'bytedance-doubao-100m-dau-china-ai', 'ByteDance''s Doubao AI assistant has crossed 100 million daily active users in China, making it the first domestic AI product to reach this milestone and intensifying competition with Baidu''s Ernie Bot.', 'ByteDance''s AI assistant Doubao has achieved 100 million daily active users in China as of March 2026, becoming the first homegrown AI product to reach this scale and signaling a major shift in the Chinese AI consumer landscape.\n\nDoubao''s growth has been propelled by deep integration with TikTok''s sister app Douyin, ByteDance''s content recommendation algorithms, and aggressive pricing—the service remains free for most consumer use cases. The platform supports text, image, video, and code generation through a unified interface.\n\nThe milestone puts pressure on Baidu''s Ernie Bot, which had been the dominant domestic AI assistant with approximately 60 million DAU as of Q4 2025. Alibaba''s Tongyi Qianwen and Tencent''s Hunyuan are also competing but trail significantly.\n\nAnalysts note that ByteDance''s distribution advantage through its existing super-apps gives Doubao a structural moat that pure-play AI companies cannot easily replicate. The company is reportedly considering spinning off its AI business as a separate entity in 2027 ahead of a potential IPO.', 'https://ft.com/bytedance-doubao-milestone', 'Financial Times', 'Teng Jing Xuan', 'https://images.unsplash.com/photo-1611262588024-d12430b98920?w=1200&q=80', 'ai', ARRAY['ByteDance','Doubao','China AI','Consumer AI','DAU'], FALSE, TRUE, NOW() - INTERVAL '2 days') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('EU AI Act Compliance Deadline Triggers Wave of Model Audits Across Financial Sector', 'eu-ai-act-compliance-financial-sector-audits', 'With the EU AI Act''s high-risk system requirements taking effect in August 2026, European banks and asset managers are scrambling to audit their AI models, creating a new compliance services market estimated at 2.3 billion euros.', 'The European Union''s AI Act is creating a new compliance services industry as financial institutions race to meet the August 2026 deadline for high-risk AI system requirements.\n\nUnder the Act, AI systems used for credit scoring, fraud detection, insurance underwriting, and investment recommendations are classified as high-risk and must undergo conformity assessments, maintain comprehensive documentation, and implement human oversight mechanisms.\n\nMajor European banks including Deutsche Bank, BNP Paribas, and ING have disclosed AI Act compliance programs running into hundreds of millions of euros. Consulting firms McKinsey, Accenture, and Deloitte have all launched dedicated AI Act practices.\n\nThe compliance burden is disproportionately hitting smaller asset managers and fintech companies that lack the legal and technical resources to navigate the regulatory requirements. Several fintech startups have indicated they may withdraw EU market offerings rather than bear compliance costs.\n\nFor AI governance software vendors, the Act has been a windfall. Companies like Credo AI, Fiddler AI, and Arthur AI have seen European customer inquiries surge over 400% since the Act''s provisions were finalized in late 2024.', 'https://reuters.com/eu-ai-act-finance-2026', 'Reuters', 'Anna Kowalski', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80', 'fintech', ARRAY['EU AI Act','Regulation','Compliance','Financial Services','Risk Management'], TRUE, TRUE, NOW() - INTERVAL '3 days') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('Waymo Expands Robotaxi Operations to 10 New US Cities by Q3 2026', 'waymo-robotaxi-expansion-10-cities-2026', 'Alphabet''s Waymo has announced plans to launch commercial robotaxi services in 10 additional US cities by Q3 2026, backed by a \$5.6B funding round and a new manufacturing agreement with Magna International.', 'Alphabet subsidiary Waymo has announced an ambitious expansion plan that will bring its commercial robotaxi service to 10 new US cities by the end of Q3 2026. The announcement is supported by a new \$5.6 billion funding round and a manufacturing scale-up agreement with auto supplier Magna International.\n\nThe new cities include Atlanta, Denver, Seattle, Miami, Boston, Chicago, Philadelphia, Houston, Phoenix, and Nashville. Waymo currently operates in San Francisco, Los Angeles, Phoenix, and Austin.\n\nThe Magna agreement is particularly significant. Under the deal, Magna will manufacture the Waymo Driver hardware suite—including lidar, radar, and camera arrays—at its Michigan facilities, reducing Waymo''s per-vehicle hardware cost by an estimated 35%.\n\nWaymo reported 150,000 paid rides per week across its current markets as of February 2026, up from 50,000 in mid-2024. Revenue per ride averages approximately \$15, suggesting annual run-rate revenue approaching \$100 million—still modest compared to the capital deployed, but growing rapidly.\n\nCompetitors Cruise (still rebuilding post-recall), Zoox (Amazon), and Chinese operator WeRide (which received US operating permits in January) are all watching Waymo''s expansion closely.', 'https://bloomberg.com/waymo-expansion-2026', 'Bloomberg', 'Keith Naughton', 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=80', 'autonomous-vehicles', ARRAY['Waymo','Robotaxi','Autonomous Vehicles','Alphabet','Expansion'], FALSE, TRUE, NOW() - INTERVAL '4 days') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('OpenAI Operator Agents Process \$2B in Enterprise Transactions in First 60 Days', 'openai-operator-agents-2b-enterprise-transactions', 'OpenAI''s Operator product, which enables AI agents to execute multi-step business workflows autonomously, has processed over \$2 billion in enterprise transactions since its February 2026 launch, surpassing initial projections by 3x.', 'OpenAI''s Operator product has dramatically exceeded internal projections in its first 60 days of commercial availability, processing over \$2 billion in enterprise transactions across procurement, travel booking, software purchasing, and HR workflows.\n\nOperator allows businesses to deploy AI agents that can autonomously navigate websites, fill forms, execute purchases, and complete multi-step business processes without human intervention on each step. The \$2 billion figure represents the aggregate value of transactions where Operator served as the execution layer.\n\nFinancial services has emerged as the largest vertical, with banks using Operator for vendor payment processing, compliance document collection, and regulatory filing workflows. E-commerce is the second largest use case, where retailers use agents to manage supplier negotiations and inventory replenishment.\n\nOpenAI CEO Sam Altman called the results "a proof point that agentic AI creates real economic value, not just impressive demos." The company is reportedly in discussions with enterprise software providers SAP, Salesforce, and ServiceNow to create native Operator integrations.\n\nCompetitors have taken notice. Microsoft has accelerated its Copilot Actions development, and Google''s Project Jarvis team has reportedly doubled in size since Operator''s launch. The race for the enterprise AI agent market is intensifying rapidly.', 'https://theinformation.com/openai-operator-2b', 'The Information', 'Amir Efrati', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80', 'ai', ARRAY['OpenAI','Operator','AI Agents','Enterprise','Automation'], TRUE, TRUE, NOW() - INTERVAL '5 days') ON CONFLICT (slug) DO NOTHING"

Invoke-SQL "INSERT INTO news (title, slug, summary, content, source_url, source_name, author, cover_image_url, industry_slug, tags, is_premium, is_published, published_at) VALUES ('TSMC Arizona Fab Achieves First 2nm Wafer Yield, On Track for 2026 Production', 'tsmc-arizona-fab-2nm-wafer-yield', 'TSMC has confirmed its Arizona fab successfully produced its first 2nm test wafers with acceptable yield rates, a milestone that positions the facility for full N2 production by Q4 2026.', 'TSMC has achieved a critical manufacturing milestone at its Arizona Fab 21 facility, successfully producing the first 2nm (N2) process test wafers with yield rates that meet commercial production thresholds, the company confirmed in a statement to investors.\n\nThe achievement is significant for several reasons. It demonstrates that TSMC''s most advanced manufacturing process can be successfully transferred to US soil—something many industry analysts had doubted given the complexity of fab operations and the challenges of replicating Taiwan''s semiconductor ecosystem.\n\nApple is expected to be the anchor customer for Arizona N2 production, with the A20 chip destined for the iPhone 18 series potentially being manufactured domestically. NVIDIA and AMD are also reportedly in discussions for N2 allocation, though their volumes would initially be modest.\n\nThe CHIPS Act provided TSMC''s US operations with approximately \$6.6 billion in grants and \$5 billion in loans. Commerce Secretary nominee has indicated additional incentive packages may be available as production scales.\n\nGeopolitical implications are significant. US-manufactured leading-edge chips would reduce dependence on Taiwan-produced silicon for defense and critical infrastructure applications, a priority that has bipartisan support in Congress.', 'https://nikkei.com/tsmc-arizona-2nm-2026', 'Nikkei Asia', 'Cheng Ting-Fang', 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=80', 'semiconductor', ARRAY['TSMC','Semiconductor','2nm','Arizona','CHIPS Act'], FALSE, TRUE, NOW() - INTERVAL '6 days') ON CONFLICT (slug) DO NOTHING"

Write-Host ""
Write-Host "=== Done! ===" -ForegroundColor Green
Write-Host "news table created and 8 test articles inserted." -ForegroundColor Green
